#!/bin/sh

GPU_PLATFORM=0
GPU_DEVICE=0
CPU_PLATFORM=2
CPU_DEVICE=0
RUNS=10

for ((i=1; i<=6; i++))
do
	VECTOR_LENGTH=$((10 ** $i))

	FILENAME=gpu_$VECTOR_LENGTH.csv

	./experiment.sh $GPU_PLATFORM $GPU_DEVICE $RUNS $VECTOR_LENGTH $FILENAME

	FILENAME=cpu_$VECTOR_LENGTH.csv

	./experiment.sh $CPU_PLATFORM $CPU_DEVICE $RUNS $VECTOR_LENGTH $FILENAME
done
